from typing import Protocol, Mapping
from pathlib import Path
from datetime import datetime

class PathResolver(Protocol):
    """Abstracts platform-specific path resolution."""
    @property
    def local_app_data(self) -> Path: ...
    @property
    def roaming_app_data(self) -> Path: ...
    @property
    def user_profile(self) -> Path: ...
    @property
    def program_files(self) -> Path: ...
    @property
    def program_files_x86(self) -> Path | None: ...
    @property
    def windows_apps(self) -> Path | None: ...
    
    def expand_env_vars(self, path: str) -> Path: ...

class FilesystemService(Protocol):
    """Abstracts filesystem operations for purity."""
    def exists(self, path: Path) -> bool: ...
    def is_file(self, path: Path) -> bool: ...
    def is_dir(self, path: Path) -> bool: ...
    def size(self, path: Path) -> int: ...
    def modified_time(self, path: Path) -> datetime: ...
    def read_text(self, path: Path) -> str: ...

class ClockService(Protocol):
    """Abstracts time."""
    def now(self) -> datetime: ...

class EnvironmentService(Protocol):
    """Abstracts environment variables."""
    def get(self, key: str, default: str | None = None) -> str | None: ...
    def get_all(self) -> Mapping[str, str]: ...

class PlatformServices(Protocol):
    """
    Provides all platform dependencies for detectors.
    This replaces direct usage of os, sys, time, and pathlib for pure domain logic.
    """
    @property
    def paths(self) -> PathResolver: ...
    
    @property
    def fs(self) -> FilesystemService: ...
    
    @property
    def clock(self) -> ClockService: ...
    
    @property
    def env(self) -> EnvironmentService: ...
